// ══════════════════════════════════════════════════════════════════════
// LearnPulse — Core Type Definitions
// src/lib/types/index.ts
//
// This file is the SINGLE SOURCE OF TRUTH for all TypeScript types
// used across the LearnPulse pipeline. Every component, hook, API route,
// and AI module imports from here.
//
// PIPELINE OVERVIEW:
//   Raw Input → HistoryEntry[] → ClassifiedEntry[] → LearningCluster[] → GeneratedPosts
//
// HOW TYPES FLOW:
//   1. Parsers produce          : HistoryEntry[]
//   2. /api/classify produces   : ClassifiedEntry[]   (extends HistoryEntry)
//   3. /api/cluster produces    : LearningCluster[]   (contains ClassifiedEntry[])
//   4. /api/generate produces   : GeneratedPosts      (based on LearningCluster[])
// ══════════════════════════════════════════════════════════════════════

// ─── Primitive Union Types ──────────────────────────────────────────────────
//
// These are the "vocabulary" of the type system — small string unions that
// restrict what values can be assigned to certain fields.

/**
 * Where did this history entry come from?
 * - 'search'  → A search query the user typed (e.g., "how does TCP work")
 * - 'visit'   → A URL the user actually clicked and visited
 *
 * This distinction matters because:
 *   - Search queries = primary learning signal (especially with AI Overviews)
 *   - URL visits     = depth signal (user went further than a quick query)
 */
export type EntrySource = 'search' | 'visit';

/**
 * What was the user's INTENT behind this search/visit?
 * The AI classifier assigns one of these labels to each entry.
 *
 * - 'learning'   → Actively trying to understand a concept ("how does X work?")
 * - 'debugging'  → Troubleshooting a specific problem ("why is Y failing?")
 * - 'exploring'  → Surveying a topic, comparing options ("best Z in 2025")
 * - 'reference'  → Looking up specific syntax/API/docs ("python dict methods")
 * - 'building'   → Searching while building something ("nextjs dynamic route params")
 * - 'noise'      → Non-learning utility search ("weather today", "pizza near me")
 */
export type LearningIntent =
  | 'learning'
  | 'debugging'
  | 'exploring'
  | 'reference'
  | 'building'
  | 'noise';

/**
 * What TYPE of content is at this URL? (Only applies to 'visit' entries)
 * The AI classifier assigns this for URL entries to indicate what kind
 * of page the user landed on.
 *
 * - 'documentation' → Official docs / API references (docs.python.org)
 * - 'tutorial'      → Step-by-step learning content (freecodecamp.org)
 * - 'qa'            → Q&A threads (stackoverflow.com, reddit)
 * - 'repository'    → Source code (github.com)
 * - 'article'       → Blog posts / essays (dev.to, substack)
 * - 'video'         → Video content (youtube.com)
 * - 'tool'          → SaaS tools / playgrounds (codepen.io, regex101.com)
 * - 'noise'         → Non-learning pages (social media, email, banking)
 */
export type ContentType =
  | 'documentation'
  | 'tutorial'
  | 'qa'
  | 'repository'
  | 'article'
  | 'video'
  | 'tool'
  | 'noise';

/**
 * How deeply did the user engage with a learning topic?
 * Computed by the clusterer based on number of queries + URL clicks.
 *
 * - 'surface'  → 1-2 queries, no URL clicks → Quick AI-answered lookup
 * - 'moderate' → 3-5 queries OR 1-2 URL clicks → Deliberate exploration
 * - 'deep'     → 5+ queries AND/OR 3+ URL clicks → Rabbit hole / deep dive
 */
export type ClusterDepth = 'surface' | 'moderate' | 'deep';

// ─── Stage 1 Type: HistoryEntry ─────────────────────────────────────────────
//
// Produced by: src/lib/parsers/
// Consumed by: src/app/api/classify/route.ts
//
// This is the raw, uninterpreted entry right after parsing user input.
// No AI has touched it yet — it's just structured history data.

export interface HistoryEntry {
  /** Unique ID for this entry (generated by parsers using crypto.randomUUID()) */
  id: string;

  /**
   * Was this a search query or a URL visit?
   * Parsers detect this by:
   *   - Lines starting with "http" or "www" → 'visit'
   *   - Everything else → 'search'
   */
  source: EntrySource;

  /**
   * The search query text. Present when source === 'search'.
   * Example: "how does TCP handshake work"
   */
  query?: string;

  /**
   * The URL visited. Present when source === 'visit'.
   * Example: "https://developer.mozilla.org/en-US/docs/Web/HTTP"
   */
  url?: string;

  /**
   * Page title (if available from CSV/JSON exports).
   * Example: "HTTP - MDN Web Docs"
   */
  title?: string;

  /**
   * When this search/visit happened (from CSV/JSON metadata).
   * May be undefined for freeform text input (no timestamps available).
   */
  timestamp?: Date;

  /** The raw original string before parsing — useful for debugging and display */
  raw: string;
}

// ─── Stage 2 Type: ClassifiedEntry ──────────────────────────────────────────
//
// Produced by: src/app/api/classify/route.ts → src/lib/ai/classifier.ts
// Consumed by: src/app/api/cluster/route.ts
//
// ClassifiedEntry EXTENDS HistoryEntry — it keeps all original fields and
// adds the AI classification results. This is a key pattern: each pipeline
// stage enriches the data rather than replacing it.

export interface ClassifiedEntry extends HistoryEntry {
  /**
   * Is this entry a learning signal?
   * - true  → Include in clustering and post generation
   * - false → Filter out (noise), but preserve for user review
   *
   * The AI sets this based on LearningIntent — entries with intent='noise'
   * will have isLearning=false. All other intents → isLearning=true.
   */
  isLearning: boolean;

  /**
   * The primary intent behind this search/visit.
   * Set by DeepSeek in the classification stage.
   */
  intent: LearningIntent;

  /**
   * What kind of content is at this URL?
   * Only present for source === 'visit' entries.
   * Undefined for source === 'search' (search queries don't have a content type).
   */
  contentType?: ContentType;

  /**
   * A short, normalized topic string inferred by the AI.
   * Example: "async programming in Python", "React state management"
   *
   * This is key for clustering — entries with similar topics get grouped
   * together even if the query wording differs.
   */
  topic: string;

  /**
   * How confident is the AI in its classification? 0.0 to 1.0.
   * Low confidence entries (< 0.5) are flagged for user review.
   */
  confidence: number;
}

// ─── Stage 3 Type: LearningCluster ──────────────────────────────────────────
//
// Produced by: src/app/api/cluster/route.ts → src/lib/ai/clusterer.ts
// Consumed by: src/app/api/generate/route.ts
//
// A LearningCluster groups related ClassifiedEntries into a named
// "learning journey" — one coherent topic the user explored in a session.
// Example: "Debugging FastAPI Performance" might group 5 related queries
// and 2 URL visits about async, connection pooling, and profiling.

export interface LearningCluster {
  /** Unique ID for this cluster (generated by the clusterer) */
  id: string;

  /**
   * Human-readable name for this learning journey.
   * Example: "Async Programming in Python"
   * The AI picks a name that captures the essence of the cluster.
   */
  name: string;

  /**
   * A narrative description of how the learning journey unfolded.
   * Example: "Started from a production timeout bug, explored connection pooling,
   * then dove into CPython source to understand the GIL's impact on I/O."
   *
   * This narrative is used as input to post generation — it gives the post
   * generator the "story arc" to write about.
   */
  narrative: string;

  /**
   * How deep was the engagement?
   * Computed from: number of queries + number of URL visits in the cluster.
   * 'deep' clusters get priority placement in posts.
   */
  depth: ClusterDepth;

  /** All classified entries that belong to this learning journey */
  entries: ClassifiedEntry[];

  /**
   * Keywords extracted from this cluster — used for hashtag generation.
   * Example: ["async", "Python", "FastAPI", "connection-pooling"]
   */
  keywords: string[];

  /**
   * What was the user probably trying to accomplish?
   * The AI infers the goal from the entries.
   * Example: "Debug a FastAPI performance issue in production"
   */
  inferredGoal: string;
}

// ─── Stage 4 Type: GeneratedPosts ───────────────────────────────────────────
//
// Produced by: src/app/api/generate/route.ts → src/lib/ai/post-generator.ts
// Consumed by: UI components (PostPreview, CopyButton)
//
// The final output of the pipeline — multiple LinkedIn posts (one per cluster)
// and one X/Twitter post.

/**
 * A single LinkedIn post generated from one learning cluster.
 *
 * WHY ONE POST PER CLUSTER?
 *   Each cluster represents a distinct learning journey (e.g., "Async Python"
 *   and "React Performance" are two different topics). Generating one post per
 *   cluster gives the user a choice of which journey to share — rather than
 *   forcing the AI to pick one and mash them together.
 *
 * ORDERING:
 *   Posts are ordered by cluster depth: deep → moderate → surface.
 *   The deepest engagement (most queries + URL visits) produces the most
 *   interesting post, so it comes first.
 *
 * EXTRA VERSIONS:
 *   If fewer than 3 clusters exist, the highest-depth cluster generates
 *   additional posts from different writing angles (see post-generator.ts)
 *   so the user always has at least 3 LinkedIn posts to choose from.
 */
export interface LinkedInPost {
  /** The main body text of the post (no hashtags) */
  body: string;
  /** Hashtags to append (3-5 items, without the # prefix) */
  hashtags: string[];
  /** Total character count of body + hashtags */
  characterCount: number;
  /** ID of the LearningCluster this post was generated from */
  clusterId: string;
  /** Human-readable cluster name — shown as a subtitle on the post card */
  clusterName: string;
}

export interface GeneratedPosts {
  /**
   * LinkedIn posts — one per learning cluster, ordered deepest-first.
   * Minimum 3 posts guaranteed (extra versions generated if fewer clusters).
   * Maximum 4 posts (capped to avoid overwhelming the UI).
   */
  linkedinPosts: LinkedInPost[];

  /** X/Twitter post — punchy, conversational, 1-3 tweets */
  x: {
    /**
     * Array of tweet strings. Usually 1 tweet, but can be 2-3 for a thread.
     * Each tweet must be ≤ 280 characters.
     */
    tweets: string[];
    /** Hashtags to append to the last tweet (1-2 max) */
    hashtags: string[];
    /** Character count of the longest individual tweet */
    characterCount: number;
  };

  /** When these posts were generated */
  generatedAt: Date;

  /** Which clusters were used as input — allows UI to show "based on X journeys" */
  basedOn: LearningCluster[];
}

// ─── API Contract Type ───────────────────────────────────────────────────────
//
// All three API routes (/classify, /cluster, /generate) use this shape
// for their responses. This consistency makes client-side error handling
// uniform — you always check `response.success` before using `response.data`.

export interface ApiResponse<T> {
  /** Did the API call succeed? */
  success: boolean;

  /**
   * The payload — only present when success === true.
   * The generic <T> is filled in per route:
   *   - /api/classify → ApiResponse<ClassifiedEntry[]>
   *   - /api/cluster  → ApiResponse<LearningCluster[]>
   *   - /api/generate → ApiResponse<GeneratedPosts>
   */
  data?: T;

  /** Human-readable error message — only present when success === false */
  error?: string;

  /** Optional metadata about the request (for debugging and monitoring) */
  meta?: {
    /** How long the server took to process this request (milliseconds) */
    processingTimeMs: number;
    /** Approximate token count used for the AI call (for cost monitoring) */
    tokensUsed?: number;
  };
}

// ─── Pipeline State Types ─────────────────────────────────────────────────────
//
// Used by: src/hooks/usePipeline.ts
// Tracks the current state of the pipeline as it runs through stages.

/**
 * Which stage is the pipeline currently in?
 *
 * State machine flow:
 *   idle → ingesting → classifying → clustering → generating → complete
 *                                                            ↘ error (at any stage)
 */
export type PipelineStage =
  | 'idle'        // No analysis running
  | 'ingesting'   // Parsing raw input into HistoryEntry[]
  | 'classifying' // Calling /api/classify
  | 'clustering'  // Calling /api/cluster
  | 'generating'  // Calling /api/generate
  | 'complete'    // Pipeline finished — posts are ready
  | 'error';      // Something went wrong — check error field

/**
 * The complete state object managed by usePipeline().
 * This is the "single source of truth" for the entire analysis process
 * — the UI reads from this to display progress, results, and errors.
 */
export interface PipelineState {
  /** Current pipeline stage */
  stage: PipelineStage;

  /** Parsed entries (available after 'ingesting' stage) */
  entries: HistoryEntry[];

  /** AI-classified entries (available after 'classifying' stage) */
  classified: ClassifiedEntry[];

  /** Grouped learning clusters (available after 'clustering' stage) */
  clusters: LearningCluster[];

  /** Generated posts (available after 'generating' stage / 'complete') */
  posts: GeneratedPosts | null;

  /** Error message if stage === 'error' */
  error: string | null;
}

// ─── User Preferences ────────────────────────────────────────────────────────
//
// Optional context the user can provide to personalize post generation.
// If provided, passed to /api/generate for the AI to incorporate.

export interface UserPreferences {
  /**
   * The user's professional role — helps the AI frame the post appropriately.
   * Example: "Senior Backend Engineer", "ML Researcher", "CS student"
   */
  professionalContext?: string;

  /**
   * Preferred tone for LinkedIn post.
   * Defaults to 'reflective' if not specified.
   */
  linkedinTone?: 'reflective' | 'educational' | 'storytelling';

  /**
   * Should the X post be a single tweet or allow threads?
   * Defaults to 'single'.
   */
  xFormat?: 'single' | 'thread';

  /**
   * Free-form instructions from the user that guide post generation.
   *
   * This is the most direct way to steer the AI's output without
   * requiring structured toggles for every possible scenario.
   *
   * Examples:
   *   "Emphasize the debugging aspect and how it solved a production issue"
   *   "Write for a data science audience — assume familiarity with ML concepts"
   *   "Focus on the React performance topic, mention the Profiler findings"
   *   "Include a call-to-action asking what tools others use for this"
   *
   * These instructions are injected verbatim into the generation prompt
   * as a high-priority directive the AI must follow.
   */
  customInstructions?: string;
}
